config/routes.rb
Rails.application.routes.draw do

  resources :schedules
  get 'joins/add_student/:id', to: 'joins#add_student', as: 'add_student'
  resources :joins

  get 'show_user/show'

  resources :remote_study do
    get 'show', to: 'remote_study#show', as: 'subject'
  end

  resources :collective

  resources :student_report

  get 'admin_panels/show_user', to: 'admin_panel#show_user', as: 'show_user'
  get 'admin_panels/add_admin/:id', to: 'admin_panel#add_admin', as: 'add_admin'
  get 'admin_panels/delete_admin/:id', to: 'admin_panel#delete_admin', as: 'delete_admin'
  get 'admin_panels/new_year', to: 'admin_panel#new_year', as: 'new_year'
  get 'admin_panels/show_my_student', to: 'admin_panel#show_my_student', as: 'my_class'
  get 'admin_panels/implementation_new_year', to: 'admin_panel#implementation_new_year', as: 'implementation_new_year'
  get 'admin_panel/add_role', to: 'admin_panel#add_role', as: "add_role"
  get 'admin_panel/new_teacher_student', to: 'admin_panel#new_teacher_student', as: 'new_teacher_student'

  resources :pdfs do
    member do
      get 'download'
    end
  end

  resources :home_works

  get 'posts/new'

  resources :posts

  get '/posts/new/', to: 'posts#new', as: 'new'
  get '/posts/destroy/:id', to: 'posts#destroy', as: 'destroy'

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
  }

  root 'study#index'

  get 'join_to_school/new/', to: 'join_to_school#new'

end

app/models/ability.rb
# frozen_string_literal: true

# good
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #  user ||= User.new # guest user (not logged in)
    #  if user.admin?
    #   can :manage, :all
    #  else
    # can :read, :all
    # end

    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :teacher
      can :manage, only: [HomeTask, Post, Pdf]
    elsif user.has_role? :hclass
      can :create, HomeTask
    else
      can :read, :all
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/home_task.rb
# frozen_string_literal: true

# good
class HomeTask < ApplicationRecord
  scope :alert, -> { where('date_task >= :now ', now: Time.now).where(class_room: 5) }
end

app/models/join.rb
# frozen_string_literal: true

# good
class Join < ApplicationRecord
end

app/models/pdf.rb
# frozen_string_literal: true

# good
class Pdf < ApplicationRecord
end

app/models/post.rb
# frozen_string_literal: true

# good
class Post < ApplicationRecord
  mount_uploader :logo, PostLogoUploader
  scope :test, -> { where('created_at >= :one_days_ago', one_days_ago: Time.now - 1.minutes)}
end

app/models/remote_study.rb
# frozen_string_literal: true

# good
class RemoteStudy < ApplicationRecord
  scope :disactive, -> { where('active_to <= :now', active: true , now: Time.now ) }
end

app/models/report.rb
# frozen_string_literal: true

# good
class Report < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
# frozen_string_literal: true

# good
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/schedule.rb
# frozen_string_literal: true

# good
class Schedule < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

# good
class User < ApplicationRecord
  has_many :schedules
  has_many :reports
  has_one :user_role
  validates :name, :email, presence: true

  mount_uploader :avatar, AvatarUploader
  rolify

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable

  scope :online_users, -> { pluck(:id).delete_if { |user_id| !User.find(user_id).online? } }

  def online?
    if current_sign_in_at.present?
      last_sign_out_at.present? ? current_sign_in_at > last_sign_out_at : true
    else
      false
    end
  end
end

app/models/user_role.rb
# frozen_string_literal: true

# good
class UserRole < ApplicationRecord
end

app/controllers/student_report_controller.rb
# frozen_string_literal: true

# godd
class StudentReportController < ApplicationController
  before_action :authenticate_user!

  def index
    @reports = Report.where(student_id: current_user.id)
  end

  def show; end

  def edit; end

  def destroy
    redirect_to root_path, notice: 'Yeeeeh' if Report.destroy(params[:id])
  end

  def update; end

  def create
    data = (params[:start_date]['when(3i)'] + '-' +
        params[:start_date]['when(2i)'] + '-' +
        params[:start_date]['when(1i)']).to_s
    @report = Report.new(student_id: params[:student_id],
                         body: params[:report][:body],
                         when: data,
                         who: params[:report][:who])

    ReportMailer.reports_mailer.deliver

    redirect_to student_report_index_path, notice: 'Зауваження створено' if @report.save
  end

  def new
    @report = Report.new
  end
end

app/helpers/collective_helper.rb
module CollectiveHelper
end

app/helpers/home_works_helper.rb
module HomeWorksHelper

  def date_of_next(day)
    date = Date.parse(day)
    delta = date > Date.today ? 0 : 7
    date + delta
    return date.strftime('%Y-%m-%d')
  end

  def bod(day)
    DateTime.now.beginning_of_week(day)
  end
end

app/helpers/joins_helper.rb
module JoinsHelper

  def check_student
    UserRole.where(user_id: current_user.id).empty? && Join.where(user_id: current_user.id).empty?
  end

  def get_users_name_for_index_action(id)
    User.find_by(id: id).name
  end
end

app/helpers/pdfs_helper.rb
module PdfsHelper
end

app/helpers/pocts_helper.rb
module PoctsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/show_user_helper.rb
module ShowUserHelper
end

app/helpers/student_report_helper.rb
module StudentReportHelper
end

app/helpers/study_helper.rb
module StudyHelper
end

app/views/student_report/_form.html.erb
<%= form_for @report, url: posts_path do |f| %>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body, class: 'ckeditor' %>
  </div>
  <div>
    <%= f.label :who %>
    <%= f.text_field :who , :value => current_user.name%>
  </div>
  <div>
    <%= f.submit "Зберегти" %>
  </div>
<% end %>

app/views/student_report/create.html.erb
<h1>Rjafgnavnsvhanghgpigpivhpaigiar</h1>
<%= @report %>
<%= render "form" %>

app/views/student_report/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/student_report/edit.html.erb
<h1>Регадагування поста</h1>
<%= render 'form' %>

app/views/student_report/index.html.erb
<% if user_signed_in? && (current_user.has_role? :admin) %>
  <%= link_to "Створити Запис", new_student_report_path, class: "btn btn-success" %>
  <br>
<% end %>
<br>
<% @reports.each do |report| %>
  <div class="card border-secondary mb-3" style="max-width: 51rem;">
    <div class="card-header"><%= link_to report.student_id %>
      <% if user_signed_in? && (current_user.has_role? :admin) %>
        <%= link_to "cancel", student_report_path(:id => report.id), method: :delete, data: {confirm: 'Ви впевнені?'}, class: 'float-right material-icons' %>
        <%= link_to "edit", edit_student_report_path(report.id), class: 'float-right material-icons' %>
      <% end %>
    </div>
    <%= link_to '', root_path  %>
    <div class="card-body">
      <p class="card-text"><%= report.body.html_safe %><br>
        Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    <div class="card-footer"><%= link_to report.who, root_path, class: 'badge badge-pill badge-success' %><form class="float-right"><%= report.when.strftime('%d-%m-%Y') %></form></div>
  </div>
<% end %>

app/views/student_report/new.html.erb
<%= form_for @report, url: student_report_index_url  do |f| %>
  <div>
    <%= f.label 'Студент' %>
    <%= f.select_tag :student_id, options_for_select(User.all.collect {|p| [p.name, p.id]}, 1) %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>
  <div>
    <%= f.label "Дата: "%>
    <%= f.date_select :when,:start_year => Date.current.year, prefix: :start_date,order: [:day, :month, :year], :use_month_names => ["Січень", "Лютий", "Березень","Квітень","Травень","Червень","Липень",
                                                                                                                                           "Серпень","Вересень","Жовтень","Лиспопад", "Грудень"] %>
  </div>
  <div>
    <%= f.label "Автор: "%>
    <%= f.text_field :who, :value => current_user.name%>
  </div>
  <div>
    <%= f.submit "Зберегти" %>
  </div>
<% end %>

app/views/student_report/show.html.erb
<p>asd</p>

app/views/student_report/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>