config/routes.rb
Rails.application.routes.draw do

  resources :schedules
  get 'joins/add_student/:id', to: 'joins#add_student', as: 'add_student'
  resources :joins

  get 'show_user/show'

  resources :remote_study do
    get 'show', to: 'remote_study#show', as: 'subject'
  end

  resources :collective

  resources :student_report

  get 'admin_panels/show_user', to: 'admin_panel#show_user', as: 'show_user'
  get 'admin_panels/add_admin/:id', to: 'admin_panel#add_admin', as: 'add_admin'
  get 'admin_panels/delete_admin/:id', to: 'admin_panel#delete_admin', as: 'delete_admin'
  get 'admin_panels/new_year', to: 'admin_panel#new_year', as: 'new_year'
  get 'admin_panels/show_my_student', to: 'admin_panel#show_my_student', as: 'my_class'
  get 'admin_panels/implementation_new_year', to: 'admin_panel#implementation_new_year', as: 'implementation_new_year'
  get 'admin_panel/add_role', to: 'admin_panel#add_role', as: "add_role"
  get 'admin_panel/new_teacher_student', to: 'admin_panel#new_teacher_student', as: 'new_teacher_student'

  resources :pdfs do
    member do
      get 'download'
    end
  end

  resources :home_works

  get 'posts/new'

  resources :posts

  get '/posts/new/', to: 'posts#new', as: 'new'
  get '/posts/destroy/:id', to: 'posts#destroy', as: 'destroy'

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
  }

  root 'study#index'

  get 'join_to_school/new/', to: 'join_to_school#new'

end

app/models/ability.rb
# frozen_string_literal: true

# good
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #  user ||= User.new # guest user (not logged in)
    #  if user.admin?
    #   can :manage, :all
    #  else
    # can :read, :all
    # end

    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :teacher
      can :manage, only: [HomeTask, Post, Pdf]
    elsif user.has_role? :hclass
      can :create, HomeTask
    else
      can :read, :all
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/home_task.rb
# frozen_string_literal: true

# good
class HomeTask < ApplicationRecord
  scope :alert, -> { where('date_task >= :now ', now: Time.now).where(class_room: 5) }
end

app/models/join.rb
# frozen_string_literal: true

# good
class Join < ApplicationRecord
end

app/models/pdf.rb
# frozen_string_literal: true

# good
class Pdf < ApplicationRecord
end

app/models/post.rb
# frozen_string_literal: true

# good
class Post < ApplicationRecord
  mount_uploader :logo, PostLogoUploader
  scope :test, -> { where('created_at >= :one_days_ago', one_days_ago: Time.now - 1.minutes)}
end

app/models/remote_study.rb
# frozen_string_literal: true

# good
class RemoteStudy < ApplicationRecord
  scope :disactive, -> { where('active_to <= :now', active: true , now: Time.now ) }
end

app/models/report.rb
# frozen_string_literal: true

# good
class Report < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
# frozen_string_literal: true

# good
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/schedule.rb
# frozen_string_literal: true

# good
class Schedule < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

# good
class User < ApplicationRecord
  has_many :schedules
  has_many :reports
  has_one :user_role
  validates :name, :email, presence: true

  mount_uploader :avatar, AvatarUploader
  rolify

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable

  scope :online_users, -> { pluck(:id).delete_if { |user_id| !User.find(user_id).online? } }

  def online?
    if current_sign_in_at.present?
      last_sign_out_at.present? ? current_sign_in_at > last_sign_out_at : true
    else
      false
    end
  end
end

app/models/user_role.rb
# frozen_string_literal: true

# good
class UserRole < ApplicationRecord
end

app/controllers/admin_panel_controller.rb
# frozen_string_literal: true

# good
class AdminPanelController < ApplicationController
  before_action :must_be_admin

  def show_my_student
    @students = User.where(class_room: current_user.class_room)
  end

  def show_user
    @users = User.all.where.not(id: current_user.id)
  end

  def add_admin
    user = User.find(params[:id])
    user.remove_role user.roles.last # user only has one role
    user.add_role(:admin)

    respond_to do |format|
      format.html { redirect_to request.referrer, notice: 'Task was successfully add.' }
      format.js
      format.json { head :no_content }
    end
  end

  def delete_admin
    user = User.find(params[:id])
    user.remove_role :admin

    respond_to do |format|
      format.html { redirect_to request.referrer, notice: 'Task was successfully destroyed.' }
      format.js
      format.json { head :no_content }
    end
  end

  def new_year
    @users = User.where(class_room: current_user.class_room)
  end

  def implementation_new_year
    User.update_all('class_room = class_room + 1')

    respond_to do |format|
      format.html { redirect_to new_year_path, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def new_teacher_student
    @user = User.all
  end

  def add_role
    UserRole.create(id_user: params[:id_user], role: params[:role], class_room: params[:class_room])
    respond_to do |format|
      format.html { redirect_to new_year_path, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/helpers/collective_helper.rb
module CollectiveHelper
end

app/helpers/home_works_helper.rb
module HomeWorksHelper

  def date_of_next(day)
    date = Date.parse(day)
    delta = date > Date.today ? 0 : 7
    date + delta
    return date.strftime('%Y-%m-%d')
  end

  def bod(day)
    DateTime.now.beginning_of_week(day)
  end
end

app/helpers/joins_helper.rb
module JoinsHelper

  def check_student
    UserRole.where(user_id: current_user.id).empty? && Join.where(user_id: current_user.id).empty?
  end

  def get_users_name_for_index_action(id)
    User.find_by(id: id).name
  end
end

app/helpers/pdfs_helper.rb
module PdfsHelper
end

app/helpers/pocts_helper.rb
module PoctsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/show_user_helper.rb
module ShowUserHelper
end

app/helpers/study_helper.rb
module StudyHelper
end

app/views/admin_panel/_button_bar.html.erb
<%= link_to 'Адмін Права', show_user_path, method: :get, class: 'btn btn-primary' %>
<%= link_to 'Новий рік ', new_year_path, method: :get, class: 'btn btn-primary' %>
<%= link_to 'Добавити Вчителя/Учня ', new_teacher_student_path, method: :get, class: 'btn btn-primary' %>

app/views/admin_panel/add_role.html.erb
<div class="card">
  <%= debug(params) %>
</div>

app/views/admin_panel/new_teacher_student.html.erb
<div class="card">
  <% @user.each do |u| %>
    <div class="card">
      <%= u.id %>
      <%= u.name %>
        <%= u.email %>
      <%= link_to "Зробити вчителем", add_role_path(:id_user => u.id, :role => "Students", :class_room => 5), method: :get, :class => 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/admin_panel/new_year.html.erb
<%= render 'button_bar' %>
<div class="card border-secondary mb-3" style="max-width: 51rem;">
  <div class="card-header"><%#= link_to show.title, post_path(show.id) %>
  </div>
  <div class="card-body">
    Ця функція дозволяє перевести усіх існуючих учнів на клас вище.
    Усі існуючі домашні, дистанційні завдання, оцінки будуть видалені із бази (безповоротно).
    <p class="card-text"><br>
      <%= link_to 'Підтвердити', implementation_new_year_path, method: :get, class: 'btn btn-primary' %>
    </p>
  </div>
  <div class="card-footer">
    <form class="float-right"></form>
  </div>
</div>

app/views/admin_panel/show_my_student.html.erb
<div class="card border-secondary mb-3" style="max-width: 51rem;">
  <div class="card-header">
  </div>
  <div class="card-body">
    <p class="card-text"><br>
      <% @students.each do |student| %>
        <%= student.id %>
        <%= student.name %>
        <%= student.email %>
      <% end %>
    </p>
  </div>
  <div class="card-footer">
    <form class="float-right"></form>
  </div>
</div>

app/views/admin_panel/show_user.html.erb
<%= render 'button_bar' %>
<div class="card border-secondary mb-3" style="max-width: 51rem;">
  <div class="card-header">
  </div>
  <div class="card-body">
    <p class="card-text"><br>
      <% @users.each do |user| %>
        <span class="idAdmin"><%= user.id %></span>
        Ім'я: <%= user.name %>
        Клас: <%= user.class_room %>
        <% if user.has_role? :admin %>
          <%= link_to "Забрати права", delete_admin_path(user.id), method: :get, remote: true, class: 'blk', id: "#{user.id}" %>
        <% else %>
          <%= link_to "Зробити адміном", add_admin_path(user.id), method: :get, remote: true, class: 'blk', id: "#{user.id}" %>
        <% end %>
        <br>
      <% end %>
    </p>
  </div>
  <div class="card-footer">
    <form class="float-right"></form>
  </div>
</div>