config/routes.rb
Rails.application.routes.draw do

  resources :schedules
  get 'joins/add_student/:id', to: 'joins#add_student', as: 'add_student'
  resources :joins

  get 'show_user/show'

  resources :remote_study do
    get 'show', to: 'remote_study#show', as: 'subject'
  end

  resources :collective

  resources :student_report

  get 'admin_panels/show_user', to: 'admin_panel#show_user', as: 'show_user'
  get 'admin_panels/add_admin/:id', to: 'admin_panel#add_admin', as: 'add_admin'
  get 'admin_panels/delete_admin/:id', to: 'admin_panel#delete_admin', as: 'delete_admin'
  get 'admin_panels/new_year', to: 'admin_panel#new_year', as: 'new_year'
  get 'admin_panels/show_my_student', to: 'admin_panel#show_my_student', as: 'my_class'
  get 'admin_panels/implementation_new_year', to: 'admin_panel#implementation_new_year', as: 'implementation_new_year'
  get 'admin_panel/add_role', to: 'admin_panel#add_role', as: "add_role"
  get 'admin_panel/new_teacher_student', to: 'admin_panel#new_teacher_student', as: 'new_teacher_student'

  resources :pdfs do
    member do
      get 'download'
    end
  end

  resources :home_works

  get 'posts/new'

  resources :posts

  get '/posts/new/', to: 'posts#new', as: 'new'
  get '/posts/destroy/:id', to: 'posts#destroy', as: 'destroy'

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
  }

  root 'study#index'

  get 'join_to_school/new/', to: 'join_to_school#new'

end

app/models/pdf.rb
# frozen_string_literal: true

# good
class Pdf < ApplicationRecord
end

app/controllers/pdfs_controller.rb
class PdfsController < ApplicationController
  before_action :set_pdf, only: %i[show edit update destroy]

  # GET /pdfs
  # GET /pdfs.json
  def index
    @file = { "docx" => '/docx.jpg', "pdf" => "/pdf.png", "xlsx" => "/xls.jpg", "pptx" => "/pptx.jpg",
              "xls" => "/xls.jpg", "ppt" => "/pptx.jpg", "doc" => '/docx.jpg'}
    @pdfs = Pdf.order(created_at: :desc)
  end

  # GET /pdfs/1
  # GET /pdfs/1.json
  def show
    @pdf = Pdf.find(params[:id])
    pdf_filename = File.join(Rails.root, "public/uploaded_pdf/#{@pdf.path}")
    send_file(pdf_filename, filename: @pdf.path.to_s, type: 'application/pdf',
                            x_sendfile: true,
                            disposition: 'inline')
  end

  def download
    @pdf = Pdf.find(params[:id])
    pdf_filename = File.join(Rails.root, "public/uploaded_pdf/#{@pdf.path}")
    send_file(pdf_filename, filename: @pdf.path.to_s,
                            type: 'application/pdf',
                            x_sendfile: true)
  end

  # GET /pdfs/new
  def new
    @pdf = Pdf.new
  end

  # GET /pdfs/1/edit
  def edit
    @pdf = Pdf.find(params[:id])
  end

  # POST /pdfs
  # POST /pdfs.json
  def create
    @pdf = Pdf.new(pdf_params)

    # save file in public folder
    uploaded_io = params[:pdf][:path]
    File.open(Rails.root.join('public',
                              'uploaded_pdf',
                              uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    @pdf.path = uploaded_io.original_filename

    redirect_to pdfs_path, notice: 'Файл успішно добавлено' if @pdf.save
  end

  # PATCH/PUT /pdfs/1
  # PATCH/PUT /pdfs/1.json
  def update
    @pdf = Pdf.find(params[:id])
    respond_to do |format|
      if @pdf.update_attributes(pdf_params)
        format.html { redirect_to @pdf, notice: 'Pdf was successfully updated.' }
        format.json { render :show, status: :ok, location: @pdf }
      else
        format.html { render :edit }
        format.json { render json: @pdf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pdfs/1
  # DELETE /pdfs/1.json
  def destroy
    @pdf = Pdf.find(params[:id])
    path_to_file = Rails.root.join('public', 'uploaded_pdf', @pdf.path.to_s)
    File.delete(path_to_file) if File.exist?(path_to_file)
    @pdf.destroy
    flash[:notice] = 'Файл успішно видалено'
    redirect_to pdfs_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pdf
    @pdf = Pdf.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def pdf_params
    params.require(:pdf).permit(:title, :description, :path, :author)
  end
end

app/helpers/pdfs_helper.rb
module PdfsHelper
end

app/views/pdfs/_form.html.erb
<%= form_with(model: pdf, local: true) do |form| %>
  <% if pdf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pdf.errors.count, "error") %> prohibited this pdf from being saved:</h2>

      <ul>
      <% pdf.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :pdf_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :pdf_description %>
  </div>

  <div class="field">
    <%= form.label :path %>
    <%= form.file_field :path, id: :pdf_description, accept: '.docx,.pdf' %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, id: :pdf_author %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pdfs/edit.html.erb
<h1>Editing Pdf</h1>

<%= render 'form', pdf: @pdf %>

<%= link_to 'Show', @pdf %> |
<%= link_to 'Back', pdfs_path %>

app/views/pdfs/index.html.erb
<%#= debug params %>
<% if user_signed_in? && (current_user.has_role? :admin) %>
  <%= link_to t('pdf.button_create_pdf'), new_pdf_path, class: 'btn btn-success' %><br>
<% end %>
<br>
<% @pdfs.each do |pdf| %>
  <div class="card border-secondary">
    <div class="card-header"><%= pdf.title %> (<%= pdf.updated_at.strftime('%m-%d-%Y') %>)
      <% if user_signed_in? && (current_user.has_role? :admin) %>
        <%= link_to "cancel", pdf_path(pdf.id), method: :delete, data: {confirm: 'Ви впевнені?'}, class: 'float-right material-icons', authenticity_token: true %>
      <% end %>
    </div>
    <div class="card-body">
      <%= image_tag("#{@file[pdf.path.split('.').last]}", :alt => "#{pdf.path.split('.').last}", :style => 'float: left; margin : 13px') %>
      <p class="card-text"><%= pdf.description %><br>
    </div>
    <div class="card-footer">
      <% if pdf.path.split('.').last == 'pdf' %>
        <%= link_to 'Відкрити', pdf_path(pdf.id), method: :get, class: 'badge badge-pill badge-success' %>
      <% end %>
      <%= link_to raw("Скачати &#128190;"), download_pdf_path(pdf.id), method: :get, class: 'badge badge-pill badge-success' %>
      <form class="float-right"><%= pdf.author %></form>
    </div>
  </div>
  <br>
<% end %>

app/views/pdfs/new.html.erb
<h1>New Pdf</h1>

<%= render 'form', pdf: @pdf %>

<%= link_to 'Back', pdfs_path %>

app/views/pdfs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @pdf.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pdf.description %>
</p>

<p>
  <strong>File:</strong>
  <%= link_to @pdf.path %>
</p>
<p>
  <strong>Author:</strong>
  <%= @pdf.author %>
</p>

<%= link_to 'Edit', edit_pdf_path(@pdf) %> |
<%= link_to 'Back', pdfs_path %>