config/routes.rb
Rails.application.routes.draw do

  resources :schedules
  get 'joins/add_student/:id', to: 'joins#add_student', as: 'add_student'
  resources :joins

  get 'show_user/show'

  resources :remote_study do
    get 'show', to: 'remote_study#show', as: 'subject'
  end

  resources :collective

  resources :student_report

  get 'admin_panels/show_user', to: 'admin_panel#show_user', as: 'show_user'
  get 'admin_panels/add_admin/:id', to: 'admin_panel#add_admin', as: 'add_admin'
  get 'admin_panels/delete_admin/:id', to: 'admin_panel#delete_admin', as: 'delete_admin'
  get 'admin_panels/new_year', to: 'admin_panel#new_year', as: 'new_year'
  get 'admin_panels/show_my_student', to: 'admin_panel#show_my_student', as: 'my_class'
  get 'admin_panels/implementation_new_year', to: 'admin_panel#implementation_new_year', as: 'implementation_new_year'
  get 'admin_panel/add_role', to: 'admin_panel#add_role', as: "add_role"
  get 'admin_panel/new_teacher_student', to: 'admin_panel#new_teacher_student', as: 'new_teacher_student'

  resources :pdfs do
    member do
      get 'download'
    end
  end

  resources :home_works

  get 'posts/new'

  resources :posts

  get '/posts/new/', to: 'posts#new', as: 'new'
  get '/posts/destroy/:id', to: 'posts#destroy', as: 'destroy'

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
  }

  root 'study#index'

  get 'join_to_school/new/', to: 'join_to_school#new'

end

app/models/ability.rb
# frozen_string_literal: true

# good
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #  user ||= User.new # guest user (not logged in)
    #  if user.admin?
    #   can :manage, :all
    #  else
    # can :read, :all
    # end

    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :teacher
      can :manage, only: [HomeTask, Post, Pdf]
    elsif user.has_role? :hclass
      can :create, HomeTask
    else
      can :read, :all
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/home_task.rb
# frozen_string_literal: true

# good
class HomeTask < ApplicationRecord
  scope :alert, -> { where('date_task >= :now ', now: Time.now).where(class_room: 5) }
end

app/models/join.rb
# frozen_string_literal: true

# good
class Join < ApplicationRecord
end

app/models/pdf.rb
# frozen_string_literal: true

# good
class Pdf < ApplicationRecord
end

app/models/post.rb
# frozen_string_literal: true

# good
class Post < ApplicationRecord
  mount_uploader :logo, PostLogoUploader
  scope :test, -> { where('created_at >= :one_days_ago', one_days_ago: Time.now - 1.minutes)}
end

app/models/remote_study.rb
# frozen_string_literal: true

# good
class RemoteStudy < ApplicationRecord
  scope :disactive, -> { where('active_to <= :now', active: true , now: Time.now ) }
end

app/models/report.rb
# frozen_string_literal: true

# good
class Report < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
# frozen_string_literal: true

# good
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/schedule.rb
# frozen_string_literal: true

# good
class Schedule < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

# good
class User < ApplicationRecord
  has_many :schedules
  has_many :reports
  has_one :user_role
  validates :name, :email, presence: true

  mount_uploader :avatar, AvatarUploader
  rolify

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable

  scope :online_users, -> { pluck(:id).delete_if { |user_id| !User.find(user_id).online? } }

  def online?
    if current_sign_in_at.present?
      last_sign_out_at.present? ? current_sign_in_at > last_sign_out_at : true
    else
      false
    end
  end
end

app/models/user_role.rb
# frozen_string_literal: true

# good
class UserRole < ApplicationRecord
end

app/helpers/collective_helper.rb
module CollectiveHelper
end

app/helpers/home_works_helper.rb
module HomeWorksHelper

  def date_of_next(day)
    date = Date.parse(day)
    delta = date > Date.today ? 0 : 7
    date + delta
    return date.strftime('%Y-%m-%d')
  end

  def bod(day)
    DateTime.now.beginning_of_week(day)
  end
end

app/helpers/joins_helper.rb
module JoinsHelper

  def check_student
    UserRole.where(user_id: current_user.id).empty? && Join.where(user_id: current_user.id).empty?
  end

  def get_users_name_for_index_action(id)
    User.find_by(id: id).name
  end
end

app/helpers/pdfs_helper.rb
module PdfsHelper
end

app/helpers/pocts_helper.rb
module PoctsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/show_user_helper.rb
module ShowUserHelper
end

app/helpers/study_helper.rb
module StudyHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Зборянська ЗОШ</title>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'%>
  <%= stylesheet_link_tag 'bootswatch', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://cdn.ckeditor.com/4.11.2/standard-all/ckeditor.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="z-index:999;">
  <div id="myModal" class="modal" >
    <div class="modal-content border-success card" style="max-width: 400px;">
      <div class="close text-right material-icons">cancel</div>
      <p style="max-width: 400px;">
        <div class="card text-white bg-danger mb-3">Заповнюйте форму тільки, якщо ви ЯВЛЯЄТЕСЬ учнем школи</div>
        <%= form_for Join.new do |f| %>
          <%= f.label 'Ваш Клас' %>
          <%= f.text_field :class_room, class: 'form-control'%><br>

          <%= f.submit_tag "Submit", class: "btn btn-primary" %>
        <% end %>
      </p>
    </div>
  </div>
  <a class="navbar-brand" href="<%= root_path %>">Сайт Школи</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= posts_path %>"><%= t('news') %>  <span class="badge badge-primary badge-pill">+10000</span><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= pdfs_path %>"><%= t('file') %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" onclick="an()"><%= t('pg') %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= collective_index_path %>"><%= t('colective') %></a>
      </li>
    </ul>
    <div id="root " >
      <ul class="navbar-nav pull-xs-right background">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to image_tag(current_user.avatar.url, class: 'bl', style: 'background-color: #18BC9C;'), edit_user_registration_path %>
          </li>
          <li class="nav-item">
            <%= link_to current_user.name, edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "power_settings_new", destroy_user_session_path, :method => :delete, class: "btn material-icons btn-link", style: "color: red" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to t('login'), new_user_session_path, class: "nav-link", id: 'login', :@click => "showLoginModal=true" %>

          </li>
          <li class="nav-item">
            <%= link_to t('reg'), new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<div id='dv' class="d-none" style=""><%= notice %></div>

<div class="row container-fluid bg" style="width: 100%">
<!--  <div class="bg">-->
  <div class="<%= user_signed_in? ? "col-lg-8 mr-4 ml-5 mt-5 " : 'col-lg-11 mr-4 ml-5 mt-5' %>">
    <%= yield %>
  </div>
  <div class="<%= user_signed_in? ? "col-lg-3 ml-0 mt-5" : 'text-hide col-lg-0 ml-0 mt-0 d-none' %>">
    <% if user_signed_in? and check_student %>
    <ul class="list-group" >
      <li class="list-group-item d-flex justify-content-between align-items-center" >
          <%= link_to t("join_class"), '#', class: 'pulse', style: "color: green;", id: "myBtn" %>
      </li>
    </ul><br>
    <% end %>
    <ul class="list-group">
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <%= link_to t("remote_study"), remote_study_index_path %>
        <span class="badge badge-primary badge-pill"></span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <%= link_to t('dz'), home_works_path %>
        <span class="badge badge-primary badge-pill"></span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <%= link_to "Розклад", schedules_path %>
        <span class="badge badge-primary badge-pill"></span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <%= link_to t('my_class'), my_class_path %>
        <span class="badge badge-primary badge-pill"></span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <%= link_to t("report"), student_report_index_path %>
        <span class="badge badge-primary badge-pill">100000000</span>
      </li>
    </ul>

    <p></p>
    <ul class="list-group">
      <li class="list-group-item d-flex justify-content-between align-items-center" style="border-color: #CC0000;" >
        <%= link_to_if (user_signed_in? and current_user.has_role? :admin), t("admin_panel"), show_user_path %>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center" style="border-color: #CC0000;" >
        <%= link_to_if (user_signed_in? and current_user.has_role? :admin), 'Нові Учні', joins_path %>
        <span class="badge badge-primary badge-pill"><%= number_willing_to_join %></span>
      </li>
    </ul>
    </br>
    <div class="jumbotron">
      <%= t('user_online') + ": #{User.online_users.count}" %>
    </div>

  </div>
<!--  </div>-->
</div><br>
<footer class="page-footer mt-5" style="height: 50px;">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="z-index:999;width: 100%">
    <div style="color: white" class="center-block">Copyright © <%= Date.today.year %></div>
  </nav>
</footer>
<script>
    var modal = document.getElementById("myModal");

    // Get the button that opens the modal
    var btn = document.getElementById("myBtn");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks on the button, open the modal
    btn.onclick = function() {
        modal.style.display = "block";
    }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
        modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }

</script>

</body>
</html>

app/views/layouts/sessionorregister.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Зборянська ЗОШ</title>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'bootswatch', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <script src="https://cdn.ckeditor.com/4.11.2/standard-all/ckeditor.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="z-index:999;">
  <a class="navbar-brand" href="<%= root_path %>">Сайт Школи</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">


    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= posts_path %>"><%= t('news') %>  <span class="badge badge-primary badge-pill">+10000</span><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= pdfs_path %>"><%= t('file') %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><%= t('pg') %></a>
      </li>
    </ul>
    <div id="root">
      <ul class="navbar-nav pull-xs-right">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= image_tag current_user.avatar.url, class: 'bl' %>
          </li>
          <li class="nav-item">
            <%= link_to current_user.name, edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "power_settings_new", destroy_user_session_path, :method => :delete, class: "btn material-icons btn-link", style: "color: red" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to t('login'), new_user_session_path, class: "nav-link", id: 'login', :@click => "showLoginModal=true" %>

          </li>
          <li class="nav-item">
            <%= link_to t('reg'), new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<div id='dv' class="d-none" style=""><%= notice %></div>
<div class="row container-fluid">
  <div class="center-block  ">
    <div class="jumbotron">
    <%= yield %>
    </div>
  </div>
</div>

</body>
</html>